---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      GitHub-Actions:
        patterns:
          - "*"
    assignees:
      - "hspaans"

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    groups:
      Python:
        patterns:
          - "*"
    assignees:
      - "hspaans"
