---
- name: Prepare
  hosts: all

  pre_tasks:
    - name: Update apt cache (on Debian).
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

    - name: Update yum cache (on Redhat).
      ansible.builtin.yum:
        update_cache: true
      when: ansible_os_family == 'RedHat'

  tasks:
    - name: Remove directories and files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /srv/app01
        - /srv/app02
