---
name: Ansible Role CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    - cron: '30 5 15 * *'

jobs:
  reusable-workflow:
    runs-on: ubuntu-latest
    name: Reusable Workflow
    steps:
      - uses: hspaans/.github/workflows/ansible-role-ci.yml@master
