# Dependency Review Action
#
# This Action will scan dependency manifest files that change as part of a Pull Request, surfacing known-vulnerable versions of the packages declared or updated in the PR. Once installed, if the workflow run is marked as required, PRs introducing known-vulnerable packages will be blocked from merging.
#
# Source repository: https://github.com/actions/dependency-review-action
# Public documentation: https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-dependency-review#dependency-review-enforcement
# SPDX overview: https://spdx.org/licenses/
---
name: Dependency Review
on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          allow-licenses: GPL-2.0, GPL-2.0-only, GPL-3.0, GPL-3.0-only, LGPL-2.1-only, LGPL-3.0-only, MIT, MPL-1.1, MPL-2.0, Apache-1.1, Apache-2.0
          comment-summary-in-pr: always
          fail-on-severity: critical
